print()

price = float(input("What is the price of a child's meal? "))
price2 = float(input("What is the price of a adult's meal? "))
number = int(input("How many children are there? "))
number2 = int(input("How many adults are there? "))
tax = float(input("What is the sales tax rate? "))
tip = float(input("What is the price of the tip you would like to give? "))
print()
value = round(price * number, 2)
value2 = round(price2 * number2, 2)
value3 = round(value + value2, 2)
print(f"Subtotal: = ${value3}")
sales_tax = round(tax * value3 / 100, 2)
print(f"Tip: ${tip}")
print(f"Sales Tax: = ${sales_tax}")
total = round(sales_tax + value3 + tip, 2)
print(f"Total: = ${total}")
print()
payment_amount = int(input("What is the payment amount? "))
change = round(payment_amount - total, 2)
print(f"Change: = (${change}")

print()
