adjective = input("Please give me a adjective: ")
animal = input("Please give me a animal: ")
verb1 = input("Please give me a verb: ")
Exclamation = input("Please give me a Exclamation: ")
verb2 = input("Please give me another verb: ")
verb3 = input("Please give me one more verb: ")
place = input("Please give me a place: ")
person = input("Please give me a person name: ")
print()
print("Your story is:")
print()
print("The other day, I was really in trouble. It all started when I saw a very")
print(f"{adjective} {animal} {verb1} down the hallway. '{Exclamation.capitalize()}!' I yelled. But all")
print(f"I could think to do was to {verb2} over and over. Miraculously,")
print(f"that caused it to stop, but not before it tried to {verb3}")
print(f"right in front of my family.")
print(f"My family then proceded to follow the {animal} to its {place} so we could talk to the {animal}.")
print(f"The {animal} turned around and said stop following me. Your friend {person}, said you wouldn't mind if I {verb1} in front of you.")
print(f"The {animal} apolgized for what he said to you and went to its {place}.")